### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by JBoRu** [RUCKBReasoning/SubgraphRetrievalKBQA#1]
It's interesting work! I want to use this subgraph retriever to conduct some experiments. But it seems not a runnable code and I can't run it successfully. The code seems not to include the retriever training process in the `trainer.py`. Can you release the runnable code or script? Thanks!

**Comment by lambdaDove** [comment]
Thanks for your attention!
Please run ```train_retriever.sh``` at code/retriever to train your dense retriever. And you can replace ```multi_hop_train.csv``` at code/retriever/data with your own data. (For example, use BFS algorithm to generate weakly supervised data (5.1 at the paper) )

**Comment by lambdaDove** [comment]
Or are you looking for pre-processing files?
The code related to data pre-processing and post-processing will be released later. 
( It will be a little bit messy. For example, you should set up your own freebase environment to traverse the  KB.
