### ISSUE TITLE
Error when executing 'run_train_nsm.py'

### ISSUE THREAD

**Issue by lirenhao1997** [RUCKBReasoning/SubgraphRetrievalKBQA#4]
Hi, thanks for sharing the code! But there seems to be something wrong when I try to reproduce your experiments.
I followed the README file and used the bash script `run.sh` for training. Then in the process of `python run_train_nsm.py`, there wasn't a 'data' folder in dir `./src/nsm_reader/NSM`, which led to the error below: 
![image](https://user-images.githubusercontent.com/34834984/188081193-a9397282-7401-45ba-94e0-bacec4e91196.png)

To solve this error, I tried to copy the original 'data' folder in [NSM repo](https://github.com/RichardHGL/WSDM2021_NSM/tree/main/NSM) to `./src/nsm_reader/NSM` in SRKBQA. However, I came across another error when I ran `python run_train_nsm.py` this time:
![image](https://user-images.githubusercontent.com/34834984/188080519-09d1eee9-e2c7-421e-ab10-29e14fb24071.png)

So could you please provide the modified scripts in dir `./src/nsm_reader/NSM/data` or tell me the reason why I came across this issue?
Thanks in advance!

**Comment by lambdaDove** [comment]
Make sure you use the correct data format in the "load_data_path" since we have modified part of the NSM code to load data.
```python
        self.train_reader = {
            "load_data_path": "tmp/reader_data/webqsp/",
            "dump_model_path": "tmp/model_ckpt/nsm/",
        }
```
I will check it again.

**Comment by lirenhao1997** [comment]
> Make sure you use the correct data format in the "load_data_path" since we have modified part of the NSM code to load data.
> 
> ```python
>         self.train_reader = {
>             "load_data_path": "tmp/reader_data/webqsp/",
>             "dump_model_path": "tmp/model_ckpt/nsm/",
>         }
> ```
> 
> I will check it again.

Thanks for your reply! @lambdaDove 
I downloaded the data folder 'tmp' from your google drive and it should be the correct data format.
So the problem is that currently the modified NSM data loading scripts are missing in this repo. I would appreciate it if you could check them at your convenience.

**Comment by lambdaDove** [comment]
OK. It just ran successfully on my server. Each question in that jsonl file is organized as follows.
```
{
    "id": "WebQTrn-73",
    "question": "what form of government was practiced in sparta",
    "entities": [
        "m.09472"
    ],
    "answers": [
        {
            "kb_id": "m.04szc",
            "text": "Monarchy"
        },
        {
            "kb_id": "m.09dcy",
            "text": "Aristocracy"
        },
        {
            "kb_id": "m.04mlzp",
            "text": "Diarchy"
        },
        {
            "kb_id": "m.06cx9",
            "text": "Republic"
        }
    ],
    "subgraph": {
        "tuples": [
            [
                "m.02r15xm",
                "travel.travel_destination.tourist_attractions",
                "m.043mdsh"
            ],
            [
                "m.02r15xm",
                "travel.travel_destination.tourist_attractions",
                "m.043q6jj"
            ]
        ],
        "entities": [
            "m.04mlzp",
            "m.043q6jj",
            "lacedaemon",
            "m.09dcy",
            "m.0dbncx",
            "m.06cx9",
            "m.03plfd",
            "m.04szc",
            "m.09472",
            "sparti",
            "m.0q3bq2w",
            "Spartan",
            "m.043mdsh",
            "m.02r15xm",
            "sparta"
        ]
    },
    "paths": [
        [
            "m.09472",
            [
                "location.country.capital",
                "location.country.form_of_government",
                "END OF HOP"
            ]
        ],
        [
            "m.09472",
            [
                "location.country.capital",
                "location.country.capital",
                "END OF HOP"
            ]
        ]
    ]
}
```

**Comment by lirenhao1997** [comment]
I have checked the format of the json file you mentioned above, and it's correct.
I think there should be a 'data' folder in the directory `./src/nsm_reader/NSM/`, **but it's missing in this repo!**
**So would you please add these modified scrpits to the repo?** Thanks a lot! @lambdaDove 
![image](https://user-images.githubusercontent.com/34834984/188123179-8e244e32-9a17-4dfe-ad34-15c66a6bd67d.png)

**Comment by lambdaDove** [comment]
I'm sorry I made a fool of myself in the gitignore file. It should work now.
Besides, the data in the original file is damaged, please use the [new data](https://drive.google.com/file/d/1qFp7eGO3_fTq_I53Wd8ePQnn-E9KD6lM/view?usp=sharing)

**Comment by lirenhao1997** [comment]
> I'm sorry I made a fool of myself in the gitignore file. It should work now. Besides, the data in the original file is damaged, please use the [new data](https://drive.google.com/file/d/1qFp7eGO3_fTq_I53Wd8ePQnn-E9KD6lM/view?usp=sharing)

Thanks for your updates, now I can run the scripts successfully!

**Comment by DuanyangYuan** [comment]
Hello, I have the following error when running run_retrieve_subgraph.py. Do you encounter it?
Traceback (most recent call last):
File "/home/horanchen/ydy/study/code/SubgraphRetrievalKBQA-main/src/run_retrieve_subgraph.py", line 9, in
run()
File "/home/horanchen/ydy/study/code/SubgraphRetrievalKBQA-main/src/run_retrieve_subgraph.py", line 5, in run
run_retrieve_subgraph()
File "/home/horanchen/ydy/study/code/SubgraphRetrievalKBQA-main/src/retrieve_subgraph/retrieve_subgraph.py", line 282, in run
train_dataset = load_jsonl(os.path.join(load_data_folder, "train_simple.json"))
File "/home/horanchen/ydy/study/code/SubgraphRetrievalKBQA-main/src/utils.py", line 8, in load_jsonl
data_list.append(json.loads(line))
File "/home/horanchen/anaconda3/envs/sugkbqa/lib/python3.10/json/init.py", line 346, in loads
return _default_decoder.decode(s)
File "/home/horanchen/anaconda3/envs/sugkbqa/lib/python3.10/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/home/horanchen/anaconda3/envs/sugkbqa/lib/python3.10/json/decoder.py", line 353, in raw_decode
obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 177891 (char 177890)
